# datasource
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC连接Mysql6以上com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/artisan?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: artisan


c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/artisan?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
  user: root
  password: artisan
  driverClass: com.mysql.cj.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.artisan.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl